spring:
  datasource:
    url: ${COMMUNITY_DB_URL}
    username: ${COMMUNITY_DB_USERNAME}
    password: ${COMMUNITY_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 3       # 서비스당 최대 10개
      minimum-idle: 2
      idle-timeout: 30000         # 30초
      max-lifetime: 600000        # 10분
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update  # 개발 중엔 update, 운영은 validate or none 권장
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

server:
  port: 8083

# user-service 연동 설정
user:
  service:
    url: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true